name: jupyter_dashboards_workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - jupyter_contrib_nbextensions
  - numpy
  - xarray
  - ipywidgets
  - plotly
  - matplotlib
  - numba